name: administrador
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/descarga.jpg
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/apple_logo.png
    - assets/app_logo.jpeg
    - assets/book.jpeg
    - assets/buy.jpeg
    - assets/dinero.jpeg
    - assets/estadisticas.jpeg
    - assets/help.jpeg
    - assets/box.jpeg

  